src/GoVoyageBundle/Entity/Voiture.php
<?php

namespace GoVoyageBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Voiture
 *
 * @ORM\Table(name="voiture", indexes={@ORM\Index(name="alv_vo_fk", columns={"alv_vo_fk"}), @ORM\Index(name="client_vo_fk", columns={"client_vo_fk"})})
 * @ORM\Entity(repositoryClass="GoVoyageBundle\Repository\VoitureRepository")
 *
 */
class Voiture
{
    /**
     * @var string
     *
     * @ORM\Column(name="id_voiture", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id_voiture;

    /**
     * @var string
     *
     * @ORM\Column(name="regNo", type="string", length=25, nullable=true)
     */
    private $regno;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="depart", type="date", nullable=true)
     */
    private $depart;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="arrivee",type="date", nullable=true)
     */
    private $arrivee;

    /**
     * @var string
     *
     * @ORM\Column(name="model", type="string", length=30, nullable=false)
     */
    private $model;

    /**
     * @var string
     *
     * @ORM\Column(name="img_voiture", type="string", length=255, nullable=true)
     */
    private $img_voiture;

    /**
     * @var integer
     *
     * @ORM\Column(name="duration", type="integer", nullable=false)
     */
    private $duration;

    /**
     * @var integer
     *
     * @ORM\Column(name="rate", type="integer", nullable=false)
     */
    private $rate;

    /**
     * @var integer
     *
     * @ORM\Column(name="type", type="integer", nullable=false)
     */
    private $type;

    /**
     * @var string
     *
     * @ORM\Column(name="status", type="string", nullable=false)
     */
    private $status;

    /**
     * @var \Users
     *
     * @ORM\ManyToOne(targetEntity="Users")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="alv_vo_fk", referencedColumnName="id_user")
     * })
     */
    private $alvVoFk;

    /**
     * @var \Users
     *
     * @ORM\ManyToOne(targetEntity="Users")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="client_vo_fk", referencedColumnName="id_user")
     * })
     */
    private $clientVoFk;




    /**
     * Get id_voiture
     *
     * @return integer
     */
    public function getId_Voiture()
    {
        return $this->id_voiture;
    }

    /**
     * Set regno
     *
     * @param string $regno
     *
     * @return Voiture
     */
    public function setRegno($regno)
    {
        $this->regno = $regno;

        return $this;
    }

    /**
     * Get regno
     *
     * @return string
     */
    public function getRegno()
    {
        return $this->regno;
    }

    /**
     * Set model
     *
     * @param string $model
     *
     * @return Voiture
     */
    public function setModel($model)
    {
        $this->model = $model;

        return $this;
    }

    /**
     * Get model
     *
     * @return string
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * Set imgVoiture
     *
     * @param string $imgVoiture
     *
     * @return Voiture
     */
    public function setImgVoiture($imgVoiture)
    {
        $this->img_voiture = $imgVoiture;

        return $this;
    }

    /**
     * Get imgVoiture
     *
     * @return string
     */
    public function getImgVoiture()
    {
        return $this->img_voiture;
    }

    /**
     * Set duration
     *
     * @param integer $duration
     *
     * @return Voiture
     */
    public function setDuration($duration)
    {
        $this->duration = $duration;

        return $this;
    }

    /**
     * Get duration
     *
     * @return integer
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * Set rate
     *
     * @param integer $rate
     *
     * @return Voiture
     */
    public function setRate($rate)
    {
        $this->rate = $rate;

        return $this;
    }

    /**
     * Get rate
     *
     * @return integer
     */
    public function getRate()
    {
        return $this->rate;
    }

    /**
     * Set type
     *
     * @param integer $type
     *
     * @return Voiture
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return integer
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set status
     *
     * @param string $status
     *
     * @return Voiture
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set alvVoFk
     *
     * @param \GoVoyageBundle\Entity\Users $alvVoFk
     *
     * @return Voiture
     */
    public function setAlvVoFk(\GoVoyageBundle\Entity\Users $alvVoFk = null)
    {
        $this->alvVoFk = $alvVoFk;

        return $this;
    }

    /**
     * Get alvVoFk
     *
     * @return \GoVoyageBundle\Entity\Users
     */
    public function getAlvVoFk()
    {
        return $this->alvVoFk;
    }

    /**
     * Set clientVoFk
     *
     * @param \GoVoyageBundle\Entity\Users $clientVoFk
     *
     * @return Voiture
     */
    public function setClientVoFk(\GoVoyageBundle\Entity\Users $clientVoFk = null)
    {
        $this->clientVoFk = $clientVoFk;

        return $this;
    }

    /**
     * Get clientVoFk
     *
     * @return \GoVoyageBundle\Entity\Users
     */
    public function getClientVoFk()
    {
        return $this->clientVoFk;
    }

    /**
     * Get idVoiture
     *
     * @return integer
     */
    public function getIdVoiture()
    {
        return $this->id_voiture;
    }



    /**
     * Set depart
     *
     * @param \DateTime $depart
     *
     * @return Voiture
     */
    public function setDepart($depart)
    {
        $this->depart = $depart;

        return $this;
    }

    /**
     * Get depart
     *
     * @return \DateTime
     */
    public function getDepart()
    {
        return $this->depart;
    }

    /**
     * Set arrivee
     *
     * @param \DateTime $arrivee
     *
     * @return Voiture
     */
    public function setArrivee($arrivee)
    {
        $this->arrivee = $arrivee;

        return $this;
    }

    /**
     * Get arrivee
     *
     * @return \DateTime
     */
    public function getArrivee()
    {
        return $this->arrivee;
    }


    public function setClient($id)
    {
        return $this->getClientVoFk()->setId($id) ;
    }
}

src/GoVoyageBundle/Form/VoitureForm.php
<?php

namespace GoVoyageBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VoitureForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder->add('regno')->add('model')->add('duration')
            ->add('rate')->add('type')->add('status')->add('alvVoFk')->add('clientVoFk')
            ->setMethod('GET')->add('enregistrer',SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {

    }

    public function getBlockPrefix()
    {
        return 'GoVoyage_bundle_voiture_form';
    }
}

src/GoVoyageBundle/Controller/VoitureController.php
<?php
/**
 * Created by PhpStorm.
 * User: nouha
 * Date: 14/11/2017
 * Time: 19:07
 */

namespace GoVoyageBundle\Controller;

use GoVoyageBundle\Entity\Users;
use GoVoyageBundle\Entity\Voiture;
use GoVoyageBundle\Form\VoitureForm;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;


class VoitureController extends Controller
{
    public function indexForAgenceAction(){
        $user=$this->getUser()->getId();
        $em=$this->getDoctrine()->getManager();
        //$voiture=$em->getRepository("GoVoyageBundle:Voiture")->findAll()
        $voiture=$em->getRepository("GoVoyageBundle:Voiture")->findIdParameter($user);
        return $this->render('GoVoyageBundle:Voiture:alvPostChild4.html.twig',array('voitures'=>$voiture));

    }
    public function indexForClientAction()
    {
        $em=$this->getDoctrine()->getManager() ;
        $voiture=$em->getRepository("GoVoyageBundle:Voiture")->findAll();
        return $this->render('GoVoyageBundle:Voiture:alvPostChild.html.twig',array('voitures'=>$voiture));
    }


    /*function ajoutAction(Request $request){
        $voiture=new Voiture();

        $form=$this->createForm(VoitureForm::class,$voiture);
        $form->handleRequest($request);
        if($form->isValid()){
            $em=$this->getDoctrine()->getManager();
            $em->persist($voiture);
            $em->flush();
            return $this->redirectToRoute('go_voyage_affichevoiture');
        }

        return $this->render("GoVoyageBundle:Voiture:ajout.html.twig",array('voiture'=>$voiture,'form'=>$form->createView()));
    }*/

    function ajoutAction(Request $request){
        $voiture=new Voiture();
         $user=$this->getUser();
        if($request->isMethod('POST')) {
            $voiture->setRegno($request->get('regNo'));
            $voiture->setModel($request->get('model'));
            $voiture->setDuration($request->get('duration'));
            $voiture->setRate($request->get('rate'));
            $voiture->setType($request->get('type'));
            $voiture->setStatus($request->get('status'));
            // $voiture->setClientVoFk($request->get('client_vo_fk'));
            $voiture->setAlvVoFk($user);
            $voiture->setImgVoiture("images/products/".$request->get('img_voiture'));
            $em = $this->getDoctrine()->getManager();
            $em->persist($voiture);
            $em->flush();
            return $this->redirectToRoute('go_voyage_affichevoitureforAgence');

        }
        return $this->render("GoVoyageBundle:Voiture:alvPostChild2.html.twig",array('voiture'=>$voiture));
    }


    function suppAction($id){
        $em=$this->getDoctrine()->getManager() ;
        $voiture=$em->getRepository("GoVoyageBundle:Voiture")->find($id);

        $em->remove($voiture);
        $em->flush();
        return $this->redirectToRoute('go_voyage_affichevoitureforAgence');



    }
    function updateForAgenceAction(Request $request,$id)
    {
        $em=$this->getDoctrine()->getManager();
        $voiture=$em->getRepository("GoVoyageBundle:Voiture")->find($id);
        $form=$this->createForm(VoitureForm::class,$voiture);

        $form->handleRequest($request);
        if($form->isValid()){
            $em=$this->getDoctrine()->getManager();
            $em->persist($voiture);
            $em->flush();
            return $this->redirectToRoute('go_voyage_affichevoitureforAgence');
        }

        return $this->render("GoVoyageBundle:Voiture:ajout.html.twig",array('form'=>$form->createView()));

    }
    function updateForAgence2Action(Request $request,$id){

        $em = $this->getDoctrine()->getManager();
        $voiture=$em->getRepository("GoVoyageBundle:Voiture")->find($id);
        if($request->isMethod('POST')) {
            $voiture->setRegno($request->get('regNo'));
            $voiture->setModel($request->get('model'));
            $voiture->setDuration($request->get('duration'));
            $voiture->setRate($request->get('rate'));
            $voiture->setType($request->get('type'));
            $voiture->setStatus($request->get('status'));
            // $voiture->setClientVoFk($request->get('client_vo_fk'));
             $voiture->setAlvVoFk($voiture->getAlvVoFk());
            $voiture->setImgVoiture($voiture->getImgVoiture());
            $em = $this->getDoctrine()->getManager();
            $em->persist($voiture);
            $em->flush();
            return $this->redirectToRoute('go_voyage_affichevoitureforAgence');

        }
        return $this->render("GoVoyageBundle:Voiture:alvPostChildModify.html.twig",array('voiture1'=>$voiture));

    }




    function ComfirmationForClientAction(Request $request){


        return $this->render("GoVoyageBundle:Voiture:alvPostChildModify.html.twig",array('voiture1'));

    }

    function RentCarForClientAction(Request $request,$id){


         $user=$this->getUser();
        $em = $this->getDoctrine()->getManager();
        $voiture=$em->getRepository("GoVoyageBundle:Voiture")->find($id);

        if($request->isMethod('POST')) {

            $voiture->setRegno($request->get('regNo'));
            $voiture->setModel($request->get('model'));
            $voiture->setDuration($request->get('duration'));
            $voiture->setRate($request->get('rate'));
            $voiture->setType($request->get('type'));
            $voiture->setStatus('0');
            $voiture->setClientVoFk($user);
            $voiture->setAlvVoFk($voiture->getAlvVoFk());
            $voiture->setImgVoiture($request->get('img_voiture'));
            $d1 = new \DateTime($request->get('depart'));
            $d1->format('Y-m-d');
            $voiture->setDepart($d1);
            $d2 = new \DateTime($request->get('arrivee'));
            $d2->format('Y-m-d');
            $voiture->setArrivee($d2);
            $d3=new \DateTime('now');
            if($d1 >= $d2 or $d1 < $d3){?><script>alert('you have a problem in one of the date');</script> <?php
                return $this->render("GoVoyageBundle:Voiture:requestRent.html.twig",array('voiture1'=>$voiture));
            }
                  $differ=$d1->diff($d2);
                  $gap=$differ->format('%a');
                  var_dump($gap);
            if ($gap>$request->get('duration')){?><script>alert('you have passed the maximum duration');</script> <?php
                return $this->render("GoVoyageBundle:Voiture:requestRent.html.twig",array('voiture1'=>$voiture));
            }

            $em = $this->getDoctrine()->getManager();
            $em->persist($voiture);
            $em->flush();
            return $this->redirectToRoute('go_voyage_affichevoitureforClient');


        }

        return $this->render("GoVoyageBundle:Voiture:requestRent.html.twig",array('voiture1'=>$voiture));

    }

    function searchForClientAction(Request $request){
        $em=$this->getDoctrine()->getManager();
        $voiture2=new Voiture();
        if($request->isMethod('GET')){
            $voiture2->setModel($request->get('model'));
            $voiture2=$em->getRepository("GoVoyageBundle:Voiture")->findBy(array('model'=>$voiture2->getModel()));

        }
        else{
            $voiture2=$em->getRepository("GoVoyageBundle:Voiture")->findAll();

        }
        return $this->render("GoVoyageBundle:Voiture:searchCarForClient.html.twig",array('voitures'=>$voiture2));

    }



}
?>

src/GoVoyageBundle/Resources/views/Voiture/ajout.html.twig
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ path('go_voyage_affichevoitureforAgence') }}">Twig CRUD</a>
        </div>
    </div>
</nav>

<div class="container">

    <div class="row">
        <div class="col-sm-12">
            {{ form_start(form) }}
            <p>{{ form_widget(form.regno) }}</p>
            {{ form_end(form) }}

        </div>
    </div>
    <h1>Formulaire de voiture</h1>
</div>
   {# {{ form_start(form) }}
    {{ form_widget(form) }}
    <input type="submit" value="Create" />
    {{ form_end(form) }}

    <ul>
        <li>
            <a href="#">Back to the list</a>
        </li>
    </ul>

#}

src/GoVoyageBundle/Resources/views/Voiture/alvPostChild4.html.twig
{% extends 'GoVoyageBundle:Voiture:alvPost.html.twig' %}


{% block head %}
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="{{asset('source/jquery.fancybox.css')}}">
    <link rel="stylesheet" href="{{asset('css/jquery.formstyler.css')}}">
    <link rel="stylesheet" href="{{asset('css/style.css')}}" />
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lora:400,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:300,400,500,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700&amp;subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <script src="{{asset('js/jquery-3.2.1.js')}}"></script>
    <script src="{{asset('js/bootstrap.min.js')}}"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

{% endblock %}

{% block title %}
{% endblock %}


{% block body %}


    <div class="main-cont">
        <div class="inner-page">

            <div class="inner-breadcrumbs">
                <div class="content-wrapper">
                    <div class="page-title">Listes des Voitures</div>
                    <div class="breadcrumbs">
                        <a href="#">Home</a> / <span></span>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>

            <div class="content-wrapper">
                <div class="portfolio-filters">
                    <nav>
                        <ul>
                            <li class="active"><a data-sort="all" href="#">All</a></li>
                            <li><a data-sort="M" href="#">countries</a></li>
                            <li><a data-sort="travel" href="#">travel</a></li>
                            <li><a data-sort="photography" href="#">photography</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="portfolio-holder portfolio-holder-three">
                <div class="portfolio-three-colls">
                    <!-- // -->
                    {% for voiture in voitures %}

                   <div class="portfolio-i photography">
                       <div class="portfolio-i-img">
                            <div class="portfolio-i-over">
                                <div class="portfolio-i-over-a">
                                    <div class="portfolio-i-over-b">
                                        <a href="{{asset(voiture.imgVoiture)}}" data-fancybox-group="gallery" class="fancybox portfolio-zoom"></a>
                                       <a class="portfolio-more"  href="{{ path('go_voyage_updatevoitureforAgence2',{ 'id': voiture.id_Voiture }) }}"> </a>
                                        <button type="button" class="booking-complete-btn" class="btn btn-info btn-lg" data-toggle="modal" data-target="#{{ voiture.regno }}">Details</button>

                                    </div>
                                </div>
                            </div>
                            <img alt="" src="{{asset(voiture.imgVoiture)}}" style="height: 300px;width: 370.14px">
                        </div>
                        <div class="portfolio-i-text">
                            <b>Model : {{ voiture.model }}
                            </b>
                            <a href="{{ path('go_voyage_suppvoiture',{ 'id': voiture.id_Voiture }) }}" style="color: darkorange">Delete</a>

                        </div>
                    </div>
                        <!-- Modal -->
                    <div class="modal fade" id="{{ voiture.regno }}" role="dialog">
                            <div class="modal-dialog">
                                <!-- /.container -->

                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        <h4 class="modal-title">{{ voiture.model }}{{app.user.id}}</h4>
                                    </div>
                                    <div class="modal-body">
                                        <b style="font-size: x-large;color: #515e5f;">The model of the Car : {{ voiture.model}}</b><br>
                                        <b style="font-size: x-large;color: #515e5f;">Rented By Client : {% if  voiture.clientVoFk!= null%}  {{ voiture.clientVoFk.nom }}{% else %}No Client Yet{% endif %}</b><br>
                                        <b style="font-size: x-large;color: #515e5f;">The registration number : {{ voiture.regno }}</b><br>
                                        <b style="font-size: x-large;color: #515e5f;">Availability : {{ voiture.status }}</b><br>
                                        {#<b style="font-size: x-large;color: #515e5f;">alv_vo_fk : {% if  voiture.alvVoFk!= null%}  {{ voiture.alvVoFk.nom }}{% else %}No Client Yet{% endif %}</b><br>#}
                                        <b style="font-size: x-large;color: #515e5f;">Number of horses : {{ voiture.type }}</b><br>
                                        <b style="font-size: x-large;color: #515e5f;">Car rating : {{ voiture.rate }}</b><br>
                                        <b style="font-size: x-large;color: #515e5f;">duration of Rent : {{ voiture.duration }}</b><br>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </div>
                                </div>

                            </div>
                        </div>
                    {% endfor %}
                </div>


            </div>
        </div>
    </div>




{% endblock %}

{% block script %}


    <script src="{{asset('js/jquery.1.7.1.js')}}"></script>
    <script src="{{asset('js/jqeury.appear.js')}}"></script>
    <script src="{{asset('js/jquery.ui.js')}}"></script>
    <script src="{{asset('js/script.js')}}"></script>
    <script src="{{asset('js/isotope.js')}}"></script>
    <script src="{{asset('source/jquery.fancybox.js')}}"></script>
    <script type="text/javascript" src="{{asset('js/twitterfeed.js')}}"></script>
    <script>
        $(window).load(function(){
            var $container = $('.portfolio-three-colls');
            $container.isotope({
                itemSelector: '.portfolio-i',
                columnWidth: 520,
                rowHeight: 220
            });
            $(".fancybox").fancybox({
                helpers:  {
                    overlay : {
                        locked : false
                    },
                    title : { type : 'over' }
                },
                beforeShow : function() {
                    this.title = (this.title ? '' + this.title + '' : '')  + (this.index + 1) + ' of ' + this.group.length;
                }
            });
            $('.portfolio-filters li a').click(function(){
                var $sort = $(this).data('sort');
                if ($sort=='all') {
                    var $sort = '*';
                    $container.isotope({ filter: $sort });
                } else {
                    $container.isotope({ filter: '.'+$sort });
                }
                $('.portfolio-filters li').removeClass('active');
                $(this).closest('li').addClass('active');
                return false;
            });
        });

    </script>
    <!-- \\ scripts \\ -->

{% endblock %}

src/GoVoyageBundle/Resources/views/Voiture/alvPostChildModify.html.twig
{% extends 'GoVoyageBundle:Voiture:alvPost.html.twig' %}


{% block head %}
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="{{asset('css/jquery.formstyler.css')}}">
    <link rel="stylesheet" href="{{asset('css/style.css')}}" />
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lora:400,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:300,400,500,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700&amp;subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;subset=latin,cyrillic' rel='stylesheet' type='text/css'>
{% endblock %}

{% block title %}
{% endblock %}


{% block body %}

    <div class="body-wrapper">
        <div class="wrapper-padding">
            <div class="page-head">
                <div class="page-title">Cars - <span>Modify Car</span></div>
                <div class="breadcrumbs">
                    <a href="#">Home</a> / <a href="{{path('go_voyage_affichevoitureforAgence')}}">Cars List</a> / <span></span>
                </div>
                <div class="clear"></div>
            </div>

            <div class="sp-page">
                <div class="sp-page-a">
                    <div class="sp-page-l">
                        <div class="sp-page-lb">
                            <div class="sp-page-p">
                                <form method="POST">
                                <div class="booking-left">
                                    <h2>Passenger Information</h2>
                                    <div class="booking-form">
                                        <div class="booking-form-i">
                                            <label>numero de la matricule:</label>
                                            <div class="input"><input type="text" value="{{ voiture1.regno }}" name="regNo"/></div>
                                        </div>
                                        <div class="booking-form-i">
                                            <label>Modele:</label>
                                            <div class="input"><input type="text" value="{{ voiture1.model }}" name="model"></div>
                                        </div>
                                        <div class="booking-form-i">
                                            <label>duration:</label>
                                            <div class="input"><input type="number" value="{{ voiture1.duration }}" name="duration"/></div>
                                        </div>

                                        <div class="booking-form-i">
                                            <label>rate:</label>
                                            <div class="input"><input type="number" value="{{ voiture1.rate }}" name="rate"/></div>
                                        </div>

                                        <div class="clear"></div>

                                        <div class="bookin-three-coll">
                                            <div class="booking-form-i">
                                                <label>type:</label>
                                                <div class="input"><input type="number" value="{{ voiture1.type }}" name="type"/></div>
                                            </div>


                                            <div class="clear"></div>
                                        </div>

                                        <a href="#" class="add-passanger">Add Passenger</a>
                                        <div class="checkbox">

                                            <label>
                                                Voiture:<br><br>
                                                <input type="checkbox" value="1" name="status"/>
                                                disponible
                                                <input type="checkbox" value="0" name="status"/>
                                                Non disponible
                                            </label>
                                        </div>
                                        <div class="booking-devider"></div>
                                    </div>

                                    <div class="booking-devider no-margin"></div>


                                    <div class="booking-complete">
                                        <input class="booking-complete-btn" value="Comfirmer ajout" type="submit"/>
                                    </div>

                                </div>
                                </form>
                            </div>
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>

                <div class="sp-page-r">



                    <div class="h-help">
                        <div class="h-help-lbl">Need Sparrow Help?</div>
                        <div class="h-help-lbl-a">We would be happy to help you!</div>
                        <div class="h-help-phone">2-800-256-124 23</div>
                        <div class="h-help-email">sparrow@mail.com</div>
                    </div>

                </div>
                <div class="clear"></div>
            </div>

        </div>
    </div>
    <style>
        input[type=number]::-webkit-inner-spin-button,
        input[type=number]::-webkit-outer-spin-button {
            -webkit-appearance: none;
            -moz-appearance: none;
            margin: 0;
        }
        input{
            border: 0;
        }
    </style>

{% endblock %}



{% block script %}
    <script src="{{asset('js/jquery.1.7.1.js')}}"></script>
    <script src="{{ asset('js/jqeury.appear.js') }}"></script>
    <script src="{{ asset('js/jquery.ui.js') }}"></script>
    <script src="{{ asset('js/script.js') }}"></script>
    <script src="{{ asset('js/jquery.formstyler.js') }}"></script>
    <script src="{{ asset('js/custom.select.js') }}"></script>
    <script type="text/javascript" src="{{asset('js/twitterfeed.js')}}"></script>
    <script>

        $(document).ready(function(){
            $('.custom-select').customSelect();

            (function($) {
                $(function() {
                    $('.checkbox input').styler({
                        selectSearch: true
                    });
                });
            })(jQuery);

            $(function() {
                $(document.body).on('appear', '.fly-in', function(e, $affected) {
                    $(this).addClass("appeared");
                });
                $('.fly-in').appear({force_process: true});
            });
        });
    </script>
{% endblock %}

src/GoVoyageBundle/Resources/views/Voiture/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
        <link rel="icon" type="image/x-icon" href="{{ asset('favicon.ico') }}" />
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>